# Создаю только самые простые плагины | MishaNeYT#5933
# За то они очень прикольные!

Settings:
  EnablePlugin: true
  # True - то игроку который стреляет по цели, не будет отображаться title.
  # False - то все игрокам будет отображаться title.
  NeedPermission: false
  # Эффект крови, когда по игроку попадают из лука.
  BloodEffect: true

  # DeathMessage - включить или отключить сообщение о смерти игрока - сообщение будет
  # показываться только убийце!
  DeathMessage: true
  # Звук когда игрок умирает - воспроизводится только для убийцы!
  SoundDeath: BLOCK_ANVIL_USE

# Сообщения
Messages:
  DeathMessage: '&7Вы убили игрока &c%player%'
  Reload: '&aВы успешно перезагрузили конфиг!'
  noPerms: '&cУ вас нет прав!'

