# Создаю только самые простые плагины | MishaNeYT#5933
# За то плагин очень прикольный, вдохновился растом!

Settings:
  EnablePlugin: true

  # Оповещение в экран о количество хп цели и о его смерти.
  EnableTitleDamage: true
  EnableTitleDeath: true

  # Эффект крови, когда по игроку попадают из лука.
  BloodEffect: true

  # DeathMessage - включить или отключить сообщение о смерти игрока - сообщение будет
  # отображаться только убийце!
  DeathMessage: true

  # Звук когда цель умирает - воспроизводится только для убийцы!
  SoundDeath: BLOCK_ANVIL_USE

# Сообщения
Messages:
  DeathMessage: '&7Вы убили игрока &c%player%'
  Reload: '&6IBHP &8| &fВы &aуспешно &fперезагрузили плагин!'
  noPerm: '&6IBHP &8| &cУ вас нет прав!'




